### ISSUE TITLE
Is there a plan to bundle it to npm repositories?

### ISSUE THREAD

**Issue by titimoby** [kpdecker/monaco-yaml#3]
Your work looks nice but not very easy to integrate in another project.
Do you have any plan to bundle it and distribute it through a npm package?

**Comment by pengx17** [comment]
This has been noted here: https://github.com/Microsoft/monaco-editor/issues/131
Unfortunately it looks like vscode team has no interests in bring in YAML to the default language package for the moment.

**Comment by pengx17** [comment]
Regarding bundling, it is already on NPM. Try install with `npm install monaco-yaml`.

**Comment by gary-fei** [comment]
> Regarding bundling, it is already on NPM. Try install with `npm install monaco-yaml`.

How should I use it in Single-page project where I don't understand test example

**Comment by pengx17** [comment]
As long as your monaco-editor dependency is loaded with AMD, you could use RequireJS to load the lib dynamically and register it into the existing monaco-editor instance. I am planning to enable ESM support in the following couple of months, but I cannot guarantee you a release date yet.

You could see [here](https://github.com/pengx17/json-schema/blob/master/main.jsx#L116) how I load the library with a pretty simple React app. Though it should be quite similar by bringing into other frameworks like Angular or Vue.

**Comment by gary-fei** [comment]
thanks for your explain,whiel i use 'vs' file in my vue-project,i find some files are not referenced correctly.

![image](https://user-images.githubusercontent.com/30195355/49208522-f00fc280-f3f2-11e8-8d42-0d5af540b1ec.png)

**Comment by gary-fei** [comment]
while use your lib-files  in  [my-vueproject](https://github.com/gary-fei/yaml-demo)，and put “lib-file” in "static file" for vue-project.I configure the path alias in "webpack",you could scan “HelloWorld.vue”。

**Comment by pengx17** [comment]
@ahmadmu in fact you could. You could treat monaco-editor as well as monaco-yaml as the app assets, and then configure them in Angular CLI. Meanwhile somewhere in your app configure the build-in RequireJS loader like what I did here: https://github.com/alauda/ng-monaco-editor/blob/master/src/monaco-provider.service.ts#L160.

AFAIK the monaco-editor team released a Webpack plugin to configure monaco-editor in ESM mode. I doubt that it won't work for Angular CLI since Webpack is abstracted from angular.json configuration. I suppose there should be a solution to overcome this issue but I haven't put too much efforts on it since AMD solution works anyway.

**Comment by ahmadmu** [comment]
@pengx17 Thanks it worked! In the package I'm using monaco is loaded with vs/loader as well apparently, so I just needed to add the code from the requires in the right places and now everything works. 👍

**Comment by matanya40** [comment]
have pengx17/monaco-yaml in angular 2+ 
I do not find such a thing
I would be happy if you send a link or something like that

**Comment by Booster2ooo** [comment]
I'd be glad to see a demo on this project embedded in an Angular app. I've been trying to make it work for few hours without success for now :'(
